{% set name = "python-libsbml" %}
{% set version = "5.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sbmlteam/python-libsbml/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: d39a3efff063fd8b9064f6f102d73928d43918f9f0e6afec8c6b7d8eeba1d4a1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make            # [unix]
    - cmake

  host:
    - python
    - setuptools
    - pip
    - swig
    - zlib

  run:
    - python
    - zlib

test:
  # Python imports
  imports:
    - libsbml

about:
  home: http://sbml.org
  license: LGPL-2.1-only
  license_file: LICENSE.txt
  license_family: LGPL
  summary: LibSBML is an application programming interface library for reading, writing, manipulating and validating content expressed in the Systems Biology Markup Language (SBML) format.
  doc_url: http://sbml.org/Software/libSBML
  dev_url: https://github.com/sbmlteam/python-libsbml/
  description: |
    LibSBML is an application programming interface library for
    reading, writing, manipulating and validating content
    expressed in the Systems Biology Markup Language (SBML)
    format.

    It is written in ISO C and C++, provides language bindings
    for Common Lisp, Java, Python, Perl, MATLAB and Octave, and
    includes many features that facilitate adoption and use of
    both SBML and the library. Developers can embed libSBML in
    their applications, saving themselves the work of
    implementing their own SBML parsing, manipulation and
    validation software.
  

extra:
  recipe-maintainers:
    - fbergmann
