{% set name = "python-libsbml" %}
{% set version = "5.19.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sbmlteam/python-libsbml/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b11a79a5421abba9f8874ebbc1c479cbdb3c1827697db74b687705632583a0e5

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

  host:
    - python
    - setuptools
    - pip
    - swig >=3.0.12

  run:
    - python

test:
  # Python imports
  imports:
    - libsbml

about:
  home: http://sbml.org
  license: LGPL-2.1-only
  license_file: LICENSE.txt
  license_family: LGPL
  summary: "LibSBML is an application programming interface library for reading, writing, manipulating and validating content expressed in the Systems Biology Markup Language (SBML) format. It is written in ISO C and C++, provides language bindings for Common Lisp, Java, Python, Perl, MATLAB and Octave, and includes many features that facilitate adoption and use of both SBML and the library. Developers can embed libSBML in their applications, saving themselves the work of implementing their own SBML parsing, manipulation and validation software."

extra:
  recipe-maintainers:
    - fbergmann
